### ISSUE TITLE
Friendly comment

### ISSUE THREAD

**Issue by brunos252** [antejavor/advent-of-code#1]
On day 3 part 1 solution, I see you using:
```
right_set = set()
    for char in right: 
        right_set.add(char)
```

This can be simplified as:
`right_set = set(right)`

Keep up the good work!

**Comment by antejavor** [comment]
Thanks for the comment, just solved [day 7](https://github.com/antejavor/advent-of-code/commit/81078ba835082016ce7fdd0d78a55c5158ad3122), used the code you are suggesting, and in the end we solved the task quite similar :D 

Thanks for the tip @brunos252! Will push a bit more in the next few days. 🦾
